### ISSUE TITLE
Migrate away from open.mapquestapi.com endpoint for geocoding

### ISSUE THREAD

**Issue by WillDHB** [Ukraine-Relief-Efforts/scraper#150]
I just got an email that they're giving this the axe in August, so we'll need to find something similar to replace it.

**Comment by shenanigansd** [comment]
The Lambda is currently failing because open.mapquestapi.com is returning 403

**Comment by WillDHB** [comment]
Seriously?  They said we had until August 31...

**Comment by Jachdich** [comment]
Can take a look at this but I didn't write the code so no promises

**Comment by Jachdich** [comment]
Ah, I was replying because shenanigans assigned me

**Comment by shenanigansd** [comment]
I just assigned you because you're marked as the project lead over the scraping projects, so I wanted to ask you to take a look.
Sorry for the confusion, I've assigned you both now.

Whichever of you wants to can work on it; or feel free to unassign yourselves as necessary.
