### ISSUE TITLE
Add outputs to .gitignore

### ISSUE THREAD

**Issue by xlanor** [Ukraine-Relief-Efforts/scraper#19]
We can actually avoid unnecessary branch conflicts if the folder structure does not change by not storing the .json file (if we are using dynamodb as a base store instead).

In that case, I would suggest that we actually just manually store the .json file only once (as a form of docs) and avoid re-generating it each time unless there is some kind of structural changes.

**Comment by clarejor** [comment]
Closing this since outputs are no longer present in master
