### ISSUE TITLE
Write scraper logic for Polish border guard

### ISSUE THREAD

**Issue by EchoRuby68** [Ukraine-Relief-Efforts/scraper#2]
https://www.gov.pl/web/udsc/ukraina2

**Comment by rengare** [comment]
https://www.gov.pl/web/udsc/ukraina-en

**Comment by vianho** [comment]
In Ukrainian
https://www.gov.pl/web/udsc/ukraina---ua

**Comment by clarejor** [comment]
closing this since #31 is merged
