### ISSUE TITLE
Merge poland_en and poland_pl

### ISSUE THREAD

**Issue by xlanor** [Ukraine-Relief-Efforts/scraper#20]
The code for these two look similar. Can we refactor them into a singular file to reuse code?

Subsequently, let's move it into a dedicated folder for scrapers to avoid cluttering the repository root.

**Comment by Jachdich** [comment]
Should the JSON files be merged as well?

**Comment by Jachdich** [comment]
Okay, I'm working on that now

**Comment by xlanor** [comment]
Awesome. I'll review the PR when it's ready, request a review from me
