### ISSUE TITLE
Write scraper logic for Romanian border guard

### ISSUE THREAD

**Issue by EchoRuby68** [Ukraine-Relief-Efforts/scraper#4]

**Comment by marcbak** [comment]
I'm picking this one up to setup text OCR for the image provided in discord

**Comment by marcbak** [comment]
I've created a PR but more work is needed, this is the site:
https://romania.iom.int/news/useful-information-people-entering-romania-ukraine
What I propose is that we download all images from the site then use Tesseract to find the following text: "following border points can be used to cross into Romania:" and then parse the proceeding text into strings
The refugee points can be also done this way, I'll keep working on that this evening

**Comment by Klarkin2** [comment]
@marcbak I think that could be a good course of action. How do you feel about trying to find a different site that contains text we can scrape, and using the image processing as a backup?

**Comment by marcbak** [comment]
My main issue is that probably the goverment websites will be the most up-to-date source of information, I'm mostly done with the OCR for  borders, I'll create a PR for that, next step is to use the same logic to extract the Refugee Center addresses and hand locate them to get lon, lat.
I'm probably not gonna be able to do this today, but I'll follow up tomorrow if noone picks it up

**Comment by clarejor** [comment]
Starting work on a romania_ro scraper for https://www.politiadefrontiera.ro/en/traficonline/?dt=1&vw=2

**Comment by Jachdich** [comment]
Fixed in #42
