### ISSUE TITLE
[MVP] Translate scraped data into all languages supported on the website

### ISSUE THREAD

**Issue by Klarkin2** [Ukraine-Relief-Efforts/scraper#41]
- Since languages are provided in API requests to Dynamo info, we need to add logic into the scraper to use DeepL or Google Translate (pick one) to translate scraped information into all supported website languages in the website language selector dropdown
- These translations should be stored in Dynamo
- Need to ensure the proper translation is returned based off of language selector to frontend

**Comment by Jachdich** [comment]
Should be done now?
