### ISSUE TITLE
Create copies of QR codes

### ISSUE THREAD

**Issue by oetherington** [Ukraine-Relief-Efforts/scraper#52]
As of this morning all of the old QR code links are returning 404.

There's probably 2 straight forward solutions to this:

1. Copy the QR codes into an S3 bucket when we scrape
2. Create a new QR code that points to the same URL

Solution 2 would also provide the infrastructure needed to create our own QR codes for other purposes in the future.

**Comment by xlanor** [comment]
I'm in favour of solution 2 here, because when we create the new qr code, we would also still need to host it somewhere, which means that we'd still need to host in s3.

I would propose that we name qr codes by some identifier (maybe hash of geolocation coordinates) to keep the naming consistent, and do versioning in s3 with a maximum of 2 old versions.

**Comment by Klarkin2** [comment]
Python library for consideration: https://pypi.org/project/qrcode/
Just did a quick google search, so this may not be the best solution, but just wanted to put this here for the smart people to look at

**Comment by oetherington** [comment]
@Klarkin2 Yes - they just linked to the location on Google Maps.

There was another discussion on Discord where it seemed that Google Maps might not be working from inside Ukraine right now, so it might be better to use a different provider instead. The embedded map on the frontend uses OpenStreetMaps, so maybe this would be a good option.

**Comment by Klarkin2** [comment]
@oetherington That sounds great, thanks for keeping track of this

**Comment by oetherington** [comment]
We might be able to invalidate this ticket actually. I've just done some tests and it turns out that it's _extremely_ easy to just generate the QR code on the client side.

Is there any reason we shouldn't just do this?

**Comment by Klarkin2** [comment]
nah, go for it if it's that easy!
