### ISSUE TITLE
Romanian and Hungarian scrapers do not return addresses

### ISSUE THREAD

**Issue by Jachdich** [Ukraine-Relief-Efforts/scraper#74]
Find out if the data is available on the website, if not then use some library to convert coordinates to addresses.

Useful links:
https://www.latlong.net/Show-Latitude-Longitude.html
https://www.gps-coordinates.net/
"geocoder" in pypi

**Comment by WillDHB** [comment]
The url for the geocoder library in pypi is https://pypi.org/project/geocoder/

**Comment by WillDHB** [comment]
Seems like they return addresses now, so I'm closing this out
