### ISSUE TITLE
Find Moldovan border guard website links

### ISSUE THREAD

**Issue by EchoRuby68** [Ukraine-Relief-Efforts/scraper#8]

**Comment by clarejor** [comment]
https://www.google.com/maps/d/u/0/viewer?mid=1S38hHlp67u7UoFgVGFC-GCU2Efsn6WeC&ll=46.97765775468629%2C28.393133849999998&z=8

there is an option to download as KML, we could then parse that

**Comment by clarejor** [comment]
to get to the above link, visit https://www.border.gov.md/harta-punctelor-de-trecere-ale-frontierei-de-stat and click "view larger map" in the upper right corner of the interactive map

**Comment by clarejor** [comment]
Ukraine-specific info: https://www.border.gov.md/ro/ucraina
